spring:
  application:
    name: customers
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: none
  datasource:
    username: 'postgres'
    password: 'postgres'
    url: jdbc:postgresql://localhost:10110/customer_db