services:
  postgres:
    image: 'postgres:17'
    container_name: 'finwise-customer-service'
    ports:
      - "10110:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customer_db
    volumes:
      - /var/lib/postgresql/data


